# Generated by Django 3.1.3 on 2020-11-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201122_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfeature',
            old_name='item',
            new_name='product_id',
        ),
    ]
