# Generated by Django 3.1.3 on 2020-11-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201122_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='product_item',
            new_name='product_id',
        ),
    ]
