# Generated by Django 3.1.3 on 2020-11-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201122_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon_code',
            new_name='gift_id',
        ),
        migrations.AddField(
            model_name='productrating',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
