# Generated by Django 3.1.3 on 2021-01-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201122_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='product_id',
            new_name='item',
        ),
    ]
